= If/else와 Enum

요즘 들어 개발 건이 참 많다. 메인 업무도 그렇고, 사이드 프로젝트도 그렇고. 일이 많으면 일이 많기 때문에 [.line-through]##빡치##힘들기도 하지만, 이 때문에 소모된다라는 느낌보다는, 공부할 게 쌓여간다는 부담감이 더 크다. 물론 새로운 업무라고 할 수는 없지만 개발을 하다 보면 항상 새로운 상황을 마주치게 되는데, 한 줄 한 줄 코딩 할 때마다 공부해야될 걸 알려준다.

게임을 하다보면 항상 미친 https://namu.wiki/jump/k7PaSMTHVqcH70%2BPETpqMdND2iIgzEiGIs5w%2F1sBV0BANeR06qj17loRm4tcUmTp[고인물]들을 보게 되는데, 나도 저렇게 할 수 있을까 생각해보면 아닌 것 같다. 그 사람들은 보통 한 번 잡기도 어려운 보스를 수 백 번씩 해보면서, 모든 패턴을 익히는 건 물론이고, 아주 디테일하게 다른 것들을 발견해내기 위해 똑같은 걸 조금씩 바꿔서 시도해보는 것도 시간 낭비라고 생각하지 않는 것 같다. 개발 공부를 하다보면, 이렇게까지 해야되나 싶은 순간들이 있는데, 이런 사소함과 집요함이 모여 뭔가 이뤄낼 수 있을거라고 생각하면서 더 깊게 파보려고 한다.


== Today I learned
`enum` 은 뭔가요? 라고 물어본다면 뭐라고 해야될까 생각해보다 검색해보니 다음과 같이 설명하고 있었다.

====
Enum::
An enum is a special "class" that represents a group of constants (unchangeable variables, like final variables).
====

그래, 상수의 그룹. 내가 얼마 전까지 `enum` 에 대해 갖고 있던 생각도 그랬다. 몇 년 전에 구축하던 프로젝트에서는 상수를 모두 `Constant` 라는 클래스에 몰아넣고, `public static final String` 으로 선언해서 사용했었다. 단순히 매직 넘버를 지우고, 상수를 한 군데서 관리하는다는 장점 외에는 아무 것도 없었다. 이 상수를 값으로 사용하는 변수들 역시 만능의 `String` 이었기 때문에, 미리 정해놓은 상수가 아니어도 모든 문자열을 받아들일 수 있었고 결국은 쫓아다니면서 값에 대한 유효성 체크를 해줘야 했다. 이와 다르게 `enum` 은 내부에 선언해놓은 상수 값만 받아들일 수 있다.

오늘 다시 한번 생각해보게 된 것은 `enum` 은 상수 그룹 그 이상의 의미를 갖고 있다는 것이다. `enum` 은 서로 간의 대체 가능한, 하지만 개별적인 특성을 가지고 있는 객체들을 그룹화해서 다형성을 구현할 수 있게 해준다. 상수라고 했듯이 불변이고, 상속이 불가능하기 때문에 추상클래스나 인터페이스처럼 막강하진 않지만.

[,java]
----
public void addUrl(String fileName, String type) {
    if (!isSupportedExtension(fileName, type)) {
        return;
    }
    ...
}

public boolean isSupportedExtension(String fileName, String type) {
    List<String> supportedExtensions;
    if ("image".equal(type)) {
        supportedExtensions = Arrays.asList("jpg", "jepg", "png");
    } else if ("video".equal(type)) {
        supportedExtensions = Arrays.asList("mp4", "wav");
    } else if ("audio".equal(type)) {
        supportedExtensions = Arrays.asList("mp4", "mp3");
    }
    return supportedExtensions.contains(getExtension(fileName));
}
----

아무 생각 없이 키보드만 치면 이런 코드를 만들게 된다. 문득 깨닫고, 이런 코드를 양산할 바에야 그냥 유튜브나 보면서 쉬었다가 하는 게 더 낫다고 생각하고 손을 뗀다.

난 `if/else` 를 꼭 병적으로 피해야 된다고 생각하진 않지만, 확장 가능성이 1이라도 있다면 다시 고민해봐야 한다고 생각한다. 만약 지원 가능한 확장자가 추가되거나, 또 다른 type 리스트가 필요하게 된다면 저 `if/else` 는 시간이 갈수록 비대해질 것이고, 또 다른 기능이 필요하게 되면 저 `if/else` 한 보따리를 가지고 돌아 다녀야된다. 다형성이 필요하다.

* 지원 가능한 확장자를 알기 위해 사용되는 메시지(인터페이스)는 동일하지만 내부적으로는 다르게 구현될 수 있는 게 필요하고,
* 그 타입은 `image`, `video`, `audio` 로 한정하고 싶다.

.ResourceType.java
[,java]
----
@Getter
public enum ResourceType {
    IMAGE(Arrays.asList("jpg", "jpeg", "png")),
    VIDEO(Arrays.asList("mp4", "wav")),
    AUDIO(Arrays.asList("mp4", "mp3"));

    private final List<String> supportedExtensions;

    ResourceType(List<String> supportedExtensions) {
        this.supportedExtensions = supportedExtensions;
    }
}
----
[,java]
----
public void addUrl(String fileName, ResourceType type) {
    if (!isSupportedExtension(fileName, type)) {
        return;
    }
    ...
}

public boolean isSupportedExtension(String fileName, ResourceType type) {
    return type.getSupportedExtensions().contains(getExtension(fileName));
}
----
* 현재 소스에서는 `type` 이 어떤 값이 들어올지 알 수 없다. 이 값은 코드가 실행될 때 동적으로 결정된다. 이 때문에 추후에 타입이 추가되거나 지원 가능한 확장자가 변경되더라도 `ResourceType` 이라는 `enum` 만 수정함으로써 메인 코드는 안 건드려도 된다.
* 여기까지 리팩토링을 하고 보니 `isSupportedExtentions` 를 결정하는 것이 이 객체가 해야될 일이 맞는지에 대한 의문이 생겨서 내일 더 봐야될 것 같다.

== 더 공부해 볼 것
* `enum` 의 활용에 대해서 더 공부해보고 싶다. 어떤 경우에는 오히려 독이 되는지도 알고 싶다.
* https://medium.com/@roanmonteiro/clean-code-with-java-replace-the-logical-condition-using-enum-if-else-statements-898bd6a85327[Clean Code with Java: Replace the logical condition using ENUM(if / else statements)]

== 참고
* https://www.w3schools.com/java/java_enums.asp[Java Enums]