= Jackson의 PropertyNamingStrategy

TIL 이긴 한데 매일 쓰지 못하고 있어 [.line-through]##짜증##죄책감이 들기 시작했다. 매일 매일 분명 배우는 건 있긴한데 글로 정리하는 게 역시 상당히 [.line-through]##귀찮은##어려운 작업이다. 일주일에 하나라도 꾸준히 써보자는 생각으로 하고 있긴 한데...

== Today I learned
일단 오늘 배운 것들 중에 기억에 남는 한 가지를 써보자면, Dto 객체에 `is` 로 시작하는 boolean 타입 변수가 있었다. 별 생각없이 MockMvc 테스트를 작성하고 있었는데, API 응답에 그 필드가 없다는 에러가 떠서 확인해보니 `is` prefix는 제거된 필드명이 있었다. 또 별 생각없이 `@JsonProperty("isXXX")` 를 붙여서 해결했는데, 이쯤되면 boolean 타입의 변수는 `is`, `has`, `should`, 뭐 이런걸 다 빼버려야 되는게 아닌가 싶다.


[,java]
----

public class FeelLikeSleeping {
    private boolean isVisible;

    public boolean isVisible() {
        return isVisible;
    }

    public void setVisible(boolean visible) {
        isVisible = visible;
    }
}
----
* 기본적으로 Lombok의 `@Getter/@Setter` 어노테이션을 사용하면 자동으로 만들어지는 Getter 메소드명은 `getIsXXX()/setIsXXX()` 가 아닌, `isXXX()/setXXX()` 다. Intellij에서 자동으로 생성해주는 Getter, Setter도 마찬가지다.
* 자바빈 컨벤션에 따르면, 클래스 프로퍼티들은 `getPropety()`, `setProperty()` 메소드로 접근할 수 있고, boolean 타입의 경우, `getProperty()` 대신에 `isProperty()` 를 사용해야 한다.
* Intellij는 필드명이 `is` 로 시작하면 Getter 자동 생성 시 `isIsVisible()` 이 아니라, `isVisible()` 로 교정해준다. Setter도 마찬가지로, `setIsVisible()` 아니라, `setVisible()` 이다. 교정해주는건 `is` 뿐이고, 그동안 boolean 변수명으로 써왔던 `has`, `should` prefix는 `isHasProperty()`, `isShouldProperty()` 이렇게 생성된다.
* `isIsProperty()` 가 좀 이상해보이긴 하지만, 내가 `isProperty` 를 필드명으로 쓰겠다는게 자동으로 저걸 교정해주는게 맞는 건가 싶긴하다. 여러 라이브러리에서 자바빈 컨벤션을 따르고 있고, `isPropety()` 를 Getter로 만들어버리면 내 변수명은 `property` 로 처리될텐데 말이다. Jackson 라이브러리도 마찬가지다.

====
In absence of a registered custom strategy, default Java property naming strategy is used, which leaves field names as is, and removes set/get/is prefix from methods (as well as lower-cases initial sequence of capitalized characters).
====
* Jackson naming strategy 설정 값이 없으면 기본적으로 메소드에서 `set/get/is` prefix를 제거한 값이 필드명이 된다.


== 참고
* https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/PropertyNamingStrategy.html[Class PropertyNamingStrategy]
* https://en.wikipedia.org/wiki/JavaBeans[JavaBeans]